apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: face-encoding
  name: face-encoding
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: face-encoding
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: face-encoding
    spec:
      containers:
        - image: veriffdocker/face-encoding-test-task:latest
          name: face-encoding
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
